import { StyleSheet } from 'react-native';

export const commonStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0A0E1A',
        paddingTop: 50,
        paddingHorizontal: 16,
    },
    headerText: {
        fontSize: 26,
        fontWeight: '600',
        color: '#FFFFFF',
        textAlign: 'center',
        marginBottom: 16,
        letterSpacing: 0.5,
    },
    headerLine: {
        width: 60,
        height: 3,
        backgroundColor: '#FFD700',
        borderRadius: 2,
    },
    card: {
        backgroundColor: '#1A202C',
        padding: 20,
        marginBottom: 12,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#2D3748',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    metalName: {
        fontSize: 18,
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: 12,
    },
    priceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    priceIcon: {
        marginRight: 8,
        fontSize: 16,
    },
    priceText: {
        fontSize: 16,
        color: '#FFFFFF',
        fontWeight: '500',
    },
    timeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    timeIcon: {
        marginRight: 8,
        fontSize: 16,
    },
    timeText: {
        fontSize: 14,
        color: '#A0AEC0',
        fontWeight: '400',
    },
    title: {
        fontSize: 24,
        fontWeight: '600',
        marginBottom: 24,
        textAlign: 'center',
        color: '#fff',
        letterSpacing: 0.3,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
        paddingVertical: 4,
    },
    detailIcon: {
        marginRight: 12,
        fontSize: 16,
        width: 20,
    },
    detailText: {
        fontSize: 16,
        color: '#FFFFFF',
        fontWeight: '400',
        flex: 1,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#0A0E1A',
    },
    loadingText: {
        color: '#A0AEC0',
        fontSize: 16,
        marginTop: 16,
        fontWeight: '400',
    },
    fallbackWarning: {
        color: '#FFD700',
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 16,
        opacity: 0.8,
    },
});